apiVersion: v1
kind: Pod
metadata:
  labels:
    run: gabrielpod
  name: gabrielpod
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
      - mountPath: /nginx-volume
        name: primeiro-emptydir
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
      requests:
        cpu: 0.3
        memory: 64Mi 
  - image: ubuntu
    name: ubuntu
    volumeMounts:
      - mountPath: /ubuntu-volume
        name: segundo-emptydir
    args:
      - sleep
      - "1800"
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: 256Mi
    - name: segundo-emptydir
      emptyDir:
        sizeLimit: 256Mi
