apiVersion: v1
kind: Pod
metadata:
  name: pod-dockerhub-secret
spec:
  containers:
  - name: container-docker-secret
    image: gbrmelo/pick-desafio2:8.0
  imagePullSecrets:
    - name: docker-hub-secret
