apiVersion: v1
kind: Pod
metadata:
  name: gabriel-pod
spec:
  containers:
  - name: gabriel-conteiner
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: gabriel-secret
          key: username
