apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: |
      xxxx # aquivo de configuração de login no dockerhub ( /home/ubuntu/.docker/config.json ) em base64
