apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    sfs: gabriel-sfs
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-pv-storage
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-pv-storage
    spec:    
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


