apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gabriel-deployment
  name: gabriel-deployment
  namespace: gabriel
spec:
  replicas: 10
  selector:
    matchLabels:
      app: gabriel-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gabriel-deployment
    spec:
      containers:
        - image: nginx:1.16.0
          name: nginx
          resources:
            limits:
              cpu: 0.5
              memory: 128Mi
            requests: 
              cpu: 0.3
              memory: 64Mi 
