version: '3'

services:
  aplicacao:
    build: ./dockerfiles
    ports:
       - "5000:5000"
    networks:
      - aplicacao
    environment:
      REDIS_HOST: database
    volumes:
      - volume:/aplicacao
    depends_on:
      - database
#    deploy:
#      resources:
#        reservations:
#         cpus: '0.1'
#          memory: 128M
#        limits:
#          cpus: '0.5'
#          memory: 256M  

  database: 
    image: redis
    command: redis-server --appendonly yes
    networks:
      - aplicacao
    volumes:
      - volume:/database
    healthcheck:
      test : ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
    aplicacao:
          driver: bridge

volumes:
  volume:


