apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: gabriel-pvc
  name: gabriel-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gabriel-sc
  selector:
    matchLabels:
      storage: nfs

