apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: gabriel-pv-nfs
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.13
    path: "/mnt/nfs"
  storageClassName: gabriel-sc
