apiVersion: v1
kind: Pod
metadata:
  name: gabriel-pod
  labels:
    pod: gabriel-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nfs-pv
        mountPath: /usr/share/nginx/html
  volumes:
    - name: nfs-pv
      persistentVolumeClaim:
        claimName: gabriel-pvc
