apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gabriel-sc
  namespace: gabriel
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

