apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: gabriel-daemonset
  name: gabriel-daemonset
  namespace: gabriel
spec:
  selector:
    matchLabels:
      app: gabriel-daemonset
  template:
    metadata:
      labels:
        app: gabriel-daemonset
    spec:
      hostNetwork: true
      containers:
      - image: prom/node-exporter:latest
        name: node-exporter
        ports:
          - containerPort: 9100
            hostPort: 9100
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: sys
            mountPath: /host/sys
            readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys 
