apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gabriel-deployment
  name: gabriel-deployment
  namespace: gabriel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gabriel-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gabriel-deployment
    spec:
      containers:
      - image: nginx:1.20.0
        name: nginx
        resources:
          limits:
            cpu: 0.5
            memory: 128Mi
          requests: 
            cpu: 0.3
            memory: 64Mi
        livenessProbe:
          tcpSocket:
            port: 80
              # httpGet:
              # path: /
              # port: 80    
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3 
        readinessProbe:
          exec:
            command:
            - curl
            - -f 
            - http://localhost:80/
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 80  
          initialDelaySeconds: 10
          

