apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: gabriel-rs
  name: gabriel-rs
  namespace: gabriel
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gabriel-rs
  template:
    metadata:
      labels:
        app: gabriel-rs
    spec:
      containers:
        - image: nginx:1.19.2
          name: nginx
          resources:
            limits:
              cpu: 0.5
              memory: 128Mi
            requests: 
              cpu: 0.3
              memory: 64Mi 
